# Generated by Django 3.1 on 2020-08-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
