# Generated by Django 3.1 on 2020-08-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0003_auto_20200805_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyaggregator',
            old_name='date',
            new_name='summaryDate',
        ),
    ]
