# Generated by Django 3.1 on 2020-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0005_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='totalBillingUnits',
            field=models.IntegerField(default=0),
        ),
    ]
