# Generated by Django 3.1 on 2020-08-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0006_dailyreport_totalbillingunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='totalBillingUnits',
            field=models.FloatField(default=0),
        ),
    ]
