# Generated by Django 3.1 on 2020-08-14 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0007_auto_20200811_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpost',
            name='signIn',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 22, 3, 13, 578947, tzinfo=utc)),
        ),
    ]
