# Generated by Django 3.1 on 2020-08-14 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0008_auto_20200814_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpost',
            name='signIn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
