# Generated by Django 3.1 on 2020-08-19 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0009_auto_20200814_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaggregator',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 5, 35, 44, 806751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyaggregator',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 5, 35, 44, 806751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 5, 35, 44, 806751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 5, 35, 44, 806751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logpost',
            name='signIn',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 5, 35, 44, 806751, tzinfo=utc)),
        ),
    ]
