# Generated by Django 3.0.3 on 2020-04-30 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=10)),
                ('birthDate', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.Person')),
                ('jobtitle', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('educAttainment', models.CharField(blank=True, max_length=20, null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
            ],
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.Person')),
                ('diagnosis', models.CharField(max_length=100)),
                ('intakeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('psychEval', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dischargeDate', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('persons.person',),
        ),
    ]
